### ISSUE TITLE
Beta Support

### ISSUE THREAD

**Issue by proall** [ByteDream/crunchyroll-go#10]
Hi, really love your work!!!!
the best CR downloader i had to use!

I want to suggest some thing:
1. Beta Support
2. Funimation Support

Thank you for your Hard Work!

**Comment by ByteDream** [comment]
Thanks for your compliments, the world just needed another (good xD) crunchy downloader & go api :)

Beta support is already implemented in the api but not in the command line interface. I look forward to add it within the next few days.
Funimation support won't be implemented since this is only a crunchy downloader. Besides this, in my country I have no access to funimation nor I know in another person in a (funimation supported) country with a funimation account who could help me

**Comment by ByteDream** [comment]
Beta url support is now available in version [v1.2.3](https://github.com/ByteDream/crunchyroll-go/releases/tag/v1.2.3)

**Comment by proall** [comment]
I can give account for funi, if you can make that it will be really great. And idk how, another downloaders downloading the video at 1.5mb/s if you have luck.
And yours just fast as f!!!
Really ty!

**Comment by proall** [comment]
Where r u from btw?

**Comment by ByteDream** [comment]
Germany

**Comment by ByteDream** [comment]
> I can give account for funi, if you can make that it will be really great. And idk how, another downloaders downloading the video at 1.5mb/s if you have luck. And yours just fast as f!!! Really ty!

I'm currently working on another project, so maybe after this i'll come back to your offer :)
And i don't know how the other downloaders are working but crunchyroll-go uses 4 goroutines by default to download which means that the anime (which is splitted into 715 - 720 tiny video files, or called segments) download performs 4 parallel segment downloads at the same time. It may be so fast because of this ¯\_(ツ)_/¯
