### ISSUE TITLE
How to download the subtitle as a softsub and in one language?

### ISSUE THREAD

**Issue by Askadelion** [ByteDream/crunchyroll-go#21]
Wie kann man es runterladen so das der Untertitel nicht eingebrannt wird also softsub wenn ich den befehl archive verwende läd er alle untertitel runter brauch aber nur einen davon xD nicht alle

**Comment by ByteDream** [comment]
This is not possible. Softsubs are only available with `archive`, thats correct, but choosing which one to download isn't implemented since the most usecases of this command needs multiple subtitle tracks. Also it does not make a major difference in file size or something if all subtitles are included instead of only one.

**Comment by Askadelion** [comment]
mhm verstehe, fand es in deiner alten version (--no-hardsub) zwar nicht überflüssig aber da kann man wohl nix ändern.

ps: nicht wundern Englisch schreiben ist nicht so mein fall
