### ISSUE TITLE
output parsing wrong

### ISSUE THREAD

**Issue by YoSiJo** [ByteDream/crunchyroll-go#8]
I Use:
`crunchyroll-go --color download --output '{series_name} - S{season_number}E{episode_number} - {title} [{resolution},{fps},{audio},{subtitle}].mkv' 'https://www.crunchyroll.com/de/love-chunibyo-other-delusions'`

But the output is:
`Love, Chunibyo & Other Delusions - SE - Chance Encounter... with Wicked Lord Shingan [1920x1080,23,de-DE,].mkv`

The `series_name` not match with the `crunchyroll-go help download` page and the both `season_number`, `episode_number` work nothing.

I think the first issue is fast to fix here: https://github.com/ByteDream/crunchyroll-go/blob/master/cmd/crunchyroll-go/cmd/download.go#L80

But for season_number and episode_number have i no idea.

**Comment by ByteDream** [comment]
Thanks for opening this issue, it's fixed now and ready to download with release [v1.2.2](https://github.com/ByteDream/crunchyroll-go/releases/tag/v1.2.2).
As you mentioned, i've forgot to add the help text for `series_name`. `season_number` and `episode_number` weren't working because the implementation to "translate" them from numbers to text was missing, this is also fixed.
